# 2044.
[package]
name = "count-number-of-maximum-bitwise-or-subsets"
version = "0.1.0"
edition = "2021"
description = "20220315 2044.count-number-of-maximum-bitwise-or-subsets"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
